# Generated by Django 5.1.7 on 2025-09-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healixapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='role',
            field=models.CharField(default='superadmin', max_length=50),
        ),
    ]
