# Generated by Django 5.1.7 on 2025-09-25 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healixapp', '0003_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healixapp.oldagehome'),
        ),
    ]
