# Generated by Django 5.1.7 on 2025-09-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healixapp', '0004_alter_nurse_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
