# Generated by Django 5.1.7 on 2025-09-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healixapp', '0007_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='emergency_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='emergency_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
