# Generated by Django 5.1.7 on 2025-09-25 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healixapp', '0008_resident_emergency_address_resident_emergency_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(max_length=20)),
                ('blood_sugar', models.FloatField()),
                ('heart_rate', models.PositiveIntegerField()),
                ('body_temperature', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healixapp.doctor')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healixapp.nurse')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healixapp.resident')),
            ],
        ),
    ]
