# Generated by Django 5.1.7 on 2025-10-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healixapp', '0010_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitals',
            old_name='body_temperature',
            new_name='oxygen_level',
        ),
    ]
