# Generated by Django 5.2.7 on 2025-10-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healixapp', '0011_rename_body_temperature_vitals_oxygen_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
