# Generated by Django 5.2.7 on 2025-10-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healixapp', '0012_alter_vitals_blood_pressure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='medication',
            new_name='medicine_name',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='instructions',
        ),
        migrations.AddField(
            model_name='prescription',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
