# Generated by Django 5.2.8 on 2025-11-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healixapp', '0013_rename_medication_prescription_medicine_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='blood_pressure',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
